#! /usr/bin/env python
"""EvoRepo command line application."""

import argparse


def main():
    """EvoRepo client application"""
    parser = argparse.ArgumentParser(description="EvoRepo")
    parser.parse_args()


if __name__ == "__main__":
    main()
