#! /usr/bin/env python
"""Jarvis command line application."""

import argparse
import sys

from jarvis import cli


class JarvisClient(cli.Application):

    """Jarvis command line application."""

    commands = []

    def setup(self):
        """Extend the parser configuration in order to expose all
        the received commands.
        """
        self._parser = argparse.ArgumentParser()
        commands = self._parser.add_subparsers(
            title="[commands]", dest="command")

        self._register_parser("commands", commands)


def main():
    """Run the Jarvis command line application."""
    jarvis = JarvisClient(sys.argv[1:])
    jarvis.run()


if __name__ == "__main__":
    main()
