#! /usr/bin/env python
"""watson: CLI executable script"""


import argparse


def main():
    parser = argparse.ArgumentParser(description="Watson manager")
    parser.parse_args()


if __name__ == "__main__":
    main()
